// Converted using ConvPNG
// This file contains all the graphics sources for easier inclusion in a project
#ifndef __sprites__
#define __sprites__
#include <stdint.h>

#define spaceshipa_width 30
#define spaceshipa_height 30
#define spaceshipa_size 902
extern uint8_t spaceshipa_data[902];
#define spaceshipa ((gfx_sprite_t*)spaceshipa_data)
#define spaceshipb_width 30
#define spaceshipb_height 30
#define spaceshipb_size 902
extern uint8_t spaceshipb_data[902];
#define spaceshipb ((gfx_sprite_t*)spaceshipb_data)
#define spaceshipc_width 30
#define spaceshipc_height 30
#define spaceshipc_size 902
extern uint8_t spaceshipc_data[902];
#define spaceshipc ((gfx_sprite_t*)spaceshipc_data)
#define spaceshipd_width 30
#define spaceshipd_height 30
#define spaceshipd_size 902
extern uint8_t spaceshipd_data[902];
#define spaceshipd ((gfx_sprite_t*)spaceshipd_data)
#define spaceshipe_width 30
#define spaceshipe_height 30
#define spaceshipe_size 902
extern uint8_t spaceshipe_data[902];
#define spaceshipe ((gfx_sprite_t*)spaceshipe_data)
#define spaceshipf_width 30
#define spaceshipf_height 30
#define spaceshipf_size 902
extern uint8_t spaceshipf_data[902];
#define spaceshipf ((gfx_sprite_t*)spaceshipf_data)
#define spaceshipg_width 30
#define spaceshipg_height 30
#define spaceshipg_size 902
extern uint8_t spaceshipg_data[902];
#define spaceshipg ((gfx_sprite_t*)spaceshipg_data)
#define spaceshiph_width 30
#define spaceshiph_height 30
#define spaceshiph_size 902
extern uint8_t spaceshiph_data[902];
#define spaceshiph ((gfx_sprite_t*)spaceshiph_data)
#define spaceshipi_width 30
#define spaceshipi_height 30
#define spaceshipi_size 902
extern uint8_t spaceshipi_data[902];
#define spaceshipi ((gfx_sprite_t*)spaceshipi_data)
#define spaceshipj_width 30
#define spaceshipj_height 30
#define spaceshipj_size 902
extern uint8_t spaceshipj_data[902];
#define spaceshipj ((gfx_sprite_t*)spaceshipj_data)
#define spaceshipk_width 30
#define spaceshipk_height 30
#define spaceshipk_size 902
extern uint8_t spaceshipk_data[902];
#define spaceshipk ((gfx_sprite_t*)spaceshipk_data)
#define spaceshipl_width 30
#define spaceshipl_height 30
#define spaceshipl_size 902
extern uint8_t spaceshipl_data[902];
#define spaceshipl ((gfx_sprite_t*)spaceshipl_data)
#define spaceshipm_width 30
#define spaceshipm_height 30
#define spaceshipm_size 902
extern uint8_t spaceshipm_data[902];
#define spaceshipm ((gfx_sprite_t*)spaceshipm_data)
#define asteroida_width 30
#define asteroida_height 30
#define asteroida_size 902
extern uint8_t asteroida_data[902];
#define asteroida ((gfx_sprite_t*)asteroida_data)
#define asteroidb_width 30
#define asteroidb_height 30
#define asteroidb_size 902
extern uint8_t asteroidb_data[902];
#define asteroidb ((gfx_sprite_t*)asteroidb_data)
#define asteroidc_width 30
#define asteroidc_height 30
#define asteroidc_size 902
extern uint8_t asteroidc_data[902];
#define asteroidc ((gfx_sprite_t*)asteroidc_data)
#define powerupa_width 15
#define powerupa_height 15
#define powerupa_size 227
extern uint8_t powerupa_data[227];
#define powerupa ((gfx_sprite_t*)powerupa_data)
#define powerupb_width 15
#define powerupb_height 15
#define powerupb_size 227
extern uint8_t powerupb_data[227];
#define powerupb ((gfx_sprite_t*)powerupb_data)
#define powerupc_width 15
#define powerupc_height 15
#define powerupc_size 227
extern uint8_t powerupc_data[227];
#define powerupc ((gfx_sprite_t*)powerupc_data)
#define powerupd_width 15
#define powerupd_height 15
#define powerupd_size 227
extern uint8_t powerupd_data[227];
#define powerupd ((gfx_sprite_t*)powerupd_data)
#define logo_width 51
#define logo_height 10
#define logo_size 512
extern uint8_t logo_data[512];
#define logo ((gfx_sprite_t*)logo_data)
#define sizeof_sprites_pal 512
extern uint16_t sprites_pal[256];

#endif
